---
title: "CBCL Subtyping Plots and Analysis"
author: "Jacob DeRosa"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = F, include = F, wanrning = F, message=F}

source('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Jake_Functions.R')
detach("package:dplyr", unload = TRUE)
library(dplyr)
```

Clustering to determine plot variable order 
```{r}

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>% select(starts_with("CBCL")) %>%  rename('Attention Problems' =CBCL_AP_T, 'Rule Breaking Behavior' = CBCL_RBB_T, 'Aggressive Behavior' = CBCL_AB_T, 'Withdrawn Depressed' = CBCL_WD_T, 'Somatic Complaints' = CBCL_SC_T, 'Thought Problems' = CBCL_TP_T, 'Anxious Depressed' =CBCL_AD_T, 'Social Problems' = CBCL_SP_T)

df = t(data)
# Dissimilarity matrix
d <- dist(df, method = "euclidean")
# Hierarchical clustering using Complete Linkage
hc1 <- hclust(d, method = "complete")

df = data.frame(t(df))
noquote(paste(hc1$order, collapse = ","))
df = df[c(6,7,8,2,3,5,1,4)]
dput(names(df))

```

CBCL Correlations 
```{r}

col <- colorRampPalette(c("#77AADD", "#4477AA", "#FFFFFF", "#BB4444", "#EE9988"))

p.mat <- cor.mtest(data)
corrplot::corrplot(cor(data), method="color", col=col(200),  
         type="upper",
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )


```

Main Plots 
```{r, echo = F, fig.height= 8, fig.width=16, warning = F, message=F}
library(tidyr)

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>% select(Subtype, starts_with("CBCL")) %>% group_by(Subtype) %>%  summarise_all(funs(mean)) %>% gather(., "Var", "Mean", -Subtype, factor_key = F) 

colors_line = c(scales::alpha("#6faac9", 1),
                scales::alpha("#7a5195", 1),
                scales::alpha("#ef5675", 1),
                scales::alpha("#ffa600", 1))
 
  
data = data %>% mutate(Var = ifelse(Var == 'CBCL_AP_T', 'Attention Problems',
                                    ifelse(Var == 'CBCL_RBB_T', 'Rule Breaking Behavior',
                                           ifelse(Var == 'CBCL_AB_T', 'Aggressive Beheavior',
                                                  ifelse(Var == 'CBCL_WD_T', 'Withdrawn Depressed',
                                                         ifelse(Var == 'CBCL_SC_T', 'Somatic Complaints',
                                                                ifelse(Var == 'CBCL_TP_T', 'Thought Problems',
                                                                       ifelse(Var == 'CBCL_AD_T', 'Anxious Depressed',
                                                                              ifelse(Var == 'CBCL_SP_T', 'Social Problems', NA)))))))))
data$Subtype = factor(data$Subtype)
#Turn your 'treatment' column into a character vector
data$Var <- as.character(data$Var)
#Then turn it back into a factor with the levels in the correct order
data$Var <- factor(data$Var, levels=unique(data$Var))

ggplot(data, aes(x=factor(Var), y=Mean, group=Subtype, color = Subtype)) + 
  geom_line(aes(color = Subtype), size = 3.5) +
  scale_colour_manual(values=colors_line) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_line(colour = "grey44", linetype = "dotted", size = 1), panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), axis.text.y = element_text(color="black", size=18), axis.ticks.length=unit(0.3,"cm"), axis.ticks.x=element_line(size=2), axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 18, face = "bold"), legend.text = element_text(size = 18, face = "bold")) + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank()) +
  theme(legend.background=element_blank()) +
  scale_y_continuous(breaks = seq(55,70,5)) + 
  expand_limits(y = c(55, 70))  + 
  theme(legend.position = "top") + 
  theme(axis.ticks.y = element_blank(), axis.line.y = element_blank()) +
  labs(y = "CBCL Total Scores", x = "") + 
  theme(axis.title.y = element_text(size = 20, face = "bold")) + 
  ggtitle("CBCL Subtype Profiles") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18, face = "bold", color = "black")) +
  theme(plot.title = element_text(size=25, face = "bold", vjust = 3, hjust = .5)) +
  theme(plot.margin=unit(c(0.5,0.5,1,1),"cm")) + 
  theme(legend.key = element_rect(fill = NA, color = NA)) + 
  scale_x_discrete(limits=c('Attention Problems', 'Rule Breaking Behavior', 'Aggressive Behavior',  
                            'Withdrawn Depressed', 'Somatic Complaints', 'Thought Problems', 
                            'Anxious Depressed', 'Social Problems'))



```

Diagnosis Plot
```{r,  fig.height= 6, fig.width= 12, echo = F}


data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes_Full.csv', header = T, sep = ",") %>% 
  mutate(Subtype = as.factor(ifelse(Subtype == 1, "Subtype 1",
                                    ifelse(Subtype == 2, "Subtype 2", 
                                           ifelse(Subtype == 3, "Subtype 3", 
                                                  ifelse(Subtype == 4, "Subtype 4", NA)))))) %>% select(URSI, Subtype)

df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% 
  mutate(Sex = ifelse(Sex == 1, "Female", "Male")) %>%
  mutate(Sex = as.factor(Sex)) 

data = merge(data, df, by = c("URSI"))

dx_cols = data[,c("ADHD_I", "ADHD_C", "ODD", "ADHD_H", "ASD", "ANX", "NT", "DEP", "Other", "LD")]

dx_counts = data %>% 
  select(URSI, Sex, Subtype, names(dx_cols)) %>% gather(., "DX", "Num", ADHD_I:LD, factor_key = T) %>% filter(Num != 0) %>%
  mutate(DX = as.factor(ifelse(DX == "ADHD_I", "ADHD Inattentive",
                     ifelse(DX == "ADHD_C", "ADHD Combined",
                            ifelse(DX == "NT", "Neurotypical",
                                   ifelse(DX == "ADHD_H", "ADHD Hyperactive",
                                          ifelse(DX == "LD", "Learning Disorders",
                                                 ifelse(DX == "ANX", "Anxiety",
                                                        ifelse(DX == "DEP", "Depression",
                                                               ifelse(DX == "ODD", "Oppositional Defiant",
                                                                      ifelse(DX == "Other", "Other Diagnosis", 
                                                                             ifelse(DX == "ASD", "Autism", NA)))))))))))) %>%
  within(., DX <- factor(DX, levels=names(sort(table(DX), decreasing=TRUE)))) %>% 
  group_by(DX , Subtype) %>% 
  summarise(Count = n()) %>%
  mutate(Perc = paste("(", round(Count / sum(Count)*100,2), "%)", sep = "")) %>% 
  unite("Comb", Count:Perc, remove = FALSE) %>% mutate(Comb = gsub("_", " ", Comb))


ggplot(dx_counts, aes(x = DX, y = Count, fill = Subtype)) + 
  geom_bar(stat = "identity") + 
  geom_text(aes(label=Comb), size = 4, hjust = -.02, fontface = "bold", check_overlap = T) +
  ylim(0,250) +
  coord_flip() + 
  facet_grid(~Subtype) +
  ggtitle("Diagnosis Counts and Percentages in CBCL Subtypes") +
  xlab("") + ylab("Count (% of Diagnosis)") + 
  scale_fill_manual(values = colors_line) + 
  scale_color_manual(values = colors_line) +
  facet_bg(fill = NA, color = NA) +
  facet_text(face = "bold", color = "black", size = 14) + 
  theme(axis.title.x = element_text(size=14, face="bold",),
        axis.title.y = element_text(size=14, face="bold",),
        title = element_text(size=14, face="bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(), 
        #axis.text.x = element_text(face="bold", color="black", size=12),
        axis.text.y = element_text(face="bold", color="black", size=12),
        axis.ticks.length=unit(0.1,"cm"),
        #axis.ticks.x=element_line(size=1.1),
        axis.ticks.y=element_line(size=1.1),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        line = element_blank(),
        axis.line =  element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = .5, size = 16),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```

Continuous Differences 
```{r}

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>%
  mutate(Subtype = as.factor(Subtype)) %>% select(URSI, starts_with("CBCL"), Subtype) 
df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") 
data = merge(data, df, by = c("URSI"))

measures = c("CBCL_AP_T", "CBCL_RBB_T", "CBCL_AB_T", "CBCL_WD_T", "CBCL_SC_T", "CBCL_TP_T", "CBCL_AD_T", "CBCL_SP_T", "Age", "IQ")

model <- lapply(measures, function(x) {
  lm(substitute(i ~ Subtype, list(i = as.name(x))), data = data)})

sapply(model, car::Anova,simplify =  F) %>% kable(format="pandoc")

truemodel.names = c("Income")
truemodel <- sapply(truemodel.names,function(x) NULL)

for(i in truemodel.names){
  truemodel[[i]] = chi(data, 'Subtype', i)
  print(truemodel)
}


```

```{r, message = F, warning = F}

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>%
  mutate(Subtype = as.factor(Subtype)) %>% select(URSI, Subtype) 
df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") 
data = merge(data, df, by = c("URSI")) %>% mutate(ASD_ADHD = ifelse(ADHD == 1 & ASD == 1, 1,0))

truemodel.names = c("Sex", "ADHD_I_NA", "ADHD_C_NA", "ODD", "ASD_NA", "ASD_ADHD", "ANX", "NT", "DEP", "Other", "LD")
truemodel <- sapply(truemodel.names,function(x) NULL)

for(i in truemodel.names){
  truemodel[[i]] = chi(data, 'Subtype', i)
}

library(plyr)
df <- ldply (truemodel, data.frame)
detach("package:plyr", unload = TRUE)
detach("package:dplyr", unload = TRUE)
library(dplyr)

df %>% rename(Diagnosis = .id) %>% rename(`Chi-Sqaure P-Value` = X..i..) %>% 
  mutate(`Chi-Sqaure P-Value` = ifelse(`Chi-Sqaure P-Value` < 0.001, "p < 0.001***",
                                       ifelse(`Chi-Sqaure P-Value` < 0.01 & `Chi-Sqaure P-Value` > 0.001, "p < 0.01**",
                                              ifelse(`Chi-Sqaure P-Value` < 0.05 & `Chi-Sqaure P-Value` > 0.001 & `Chi-Sqaure P-Value` > 0.01, "p < 0.05*",
                                                     ifelse(`Chi-Sqaure P-Value` > 0.05, "p > 0.05", NA))))) %>% kable(format="pandoc")
```

```{r, echo = F, fig.height= 8, fig.width=16,message=F, warning = F}

library(tidyr)

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>% mutate(Subtype = as.factor(Subtype)) %>% select(URSI, Subtype)
wiat = read.csv("/Users/jacob.derosa/Downloads/WIAT_r8.csv", header = T, sep = ",") %>% select(URSI, ends_with("_stnd")) %>% na.omit() 
wisc = read.csv("/Users/jacob.derosa/Downloads/WISC_r8.csv", header = T, sep = ",") %>% select(URSI, WISC_VSI, WISC_VCI, WISC_FRI, WISC_WMI, WISC_PSI) %>% na.omit() 
cog_subs = merge(wiat, wisc, by = c("URSI")) 

data = merge(data, cog_subs, by = c("URSI")) %>% select(-URSI) %>% mutate_at(c(2:14), funs(c(scale(.)))) %>% 
  group_by(Subtype) %>% summarise_all(funs(mean)) 

data = gather(data, "Var", "Mean", WIAT_Num_Stnd:WISC_PSI, factor_key = F) 

data = data %>% mutate(Var = ifelse(Var == "WIAT_Spell_Stnd", 'WIAT: Spelling',
                                    ifelse(Var == 'WIAT_Pseudo_Stnd', 'WIAT: Pseudoword Decoding',
                                           ifelse(Var == 'WIAT_Word_Stnd', 'WIAT: Word Reading',
                                                  ifelse(Var == 'WISC_WMI', "WISC: Working Memory Index",
                                                         ifelse(Var == 'WIAT_Num_Stnd', "WIAT: Numeracy",
                                                                ifelse(Var == 'WIAT_MP_Stnd', "WAIT: Math Problem Solving",
                                                                       ifelse(Var == 'WISC_VSI', "WISC: Visual Spatial Index",
                                                                              ifelse(Var == 'WISC_FRI', "WISC: Fluid Reasoning Index", 
                                                                                     ifelse(Var == 'WIAT_RC_Stnd', "WIAT: Reading Comprehension",
                                                                                            ifelse(Var == 'WISC_VCI', "WISC: Verbal Comprehension Index",
                                                                                                   ifelse(Var == 'WIAT_LCODC_Stnd', "WIAT: Oral Expression",
                                                                                                          ifelse(Var == 'WIAT_LC_Stnd', "WIAT: Listening Comprehension", 
                                                                                                                 ifelse(Var == 'WISC_PSI', "WISC: Processing Speed Index", NA))))))))))))))

data$Subtype = factor(data$Subtype)
#Turn your 'treatment' column into a character vector
data$Var <- as.character(data$Var)
#Then turn it back into a factor with the levels in the correct order
data$Var <- factor(data$Var, levels=unique(data$Var))

ggplot(data, aes(x=factor(Var), y=Mean, group=Subtype)) + 
  geom_line(aes(color = Subtype), size = 3.5) +
  scale_colour_manual(values=colors_line) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_line(colour = "grey44", linetype = "dotted", size = 1), panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), axis.text.y = element_text(color="black", size=18), axis.ticks.length=unit(0.3,"cm"), axis.ticks.x=element_line(size=2), axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 18, face = "bold"), legend.text = element_text(size = 18, face = "bold")) + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank()) +
  theme(legend.background=element_blank()) +
  #scale_y_continuous(breaks = seq(-1.0, 1.5,.5)) + 
  #expand_limits(y = c(-1.0, 1, .5))  + 
  theme(legend.position = "top") + 
  theme(axis.ticks.y = element_blank(), axis.line.y = element_blank()) +
  labs(y = "Z-Scores", x = "") + 
  theme(axis.title.y = element_text(size = 20, face = "bold")) + 
  ggtitle("CBCL Subtypes Intelligence and Academic Achievement Profile") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18, face = "bold", color = "black")) +
  theme(plot.title = element_text(size=20, face = "bold", vjust = 3, hjust = -.06)) +
  theme(plot.margin=unit(c(1,1,1,3),"cm")) + 
  theme(legend.key = element_rect(fill = NA, color = NA)) + scale_x_discrete(limits = c("WISC: Processing Speed Index", "WISC: Visual Spatial Index", "WISC: Fluid Reasoning Index", "WIAT: Reading Comprehension","WISC: Verbal Comprehension Index", "WIAT: Oral Expression", "WIAT: Listening Comprehension","WIAT: Spelling", 'WIAT: Pseudoword Decoding','WIAT: Word Reading', "WISC: Working Memory Index", "WIAT: Numeracy", "WAIT: Math Problem Solving"))

```


```{r}

data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Subtype_Data/CBCL_Subtypes.csv', header = T, sep = ",") %>% 
  mutate(Subtype = as.factor(ifelse(Subtype == 1, "Subtype 1",
                                    ifelse(Subtype == 2, "Subtype 2", 
                                           ifelse(Subtype == 3, "Subtype 3", 
                                                  ifelse(Subtype == 4, "Subtype 4", NA)))))) %>% select(URSI, Subtype)

df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% 
  mutate(Sex = ifelse(Sex == 1, "Female", "Male")) %>%
  mutate(Sex = as.factor(Sex)) 

data = merge(data, df, by = c("URSI"))

ggplot(data, aes(Age, fill = Subtype, color = Subtype)) +
  geom_histogram(binwidth = 1, alpha = 1)+ 
  facet_wrap(~Subtype, ncol=2) +
  ggtitle("Diagnosis Age Distribution in CBCL Subtypes") +
  xlab("Chronological Age") + ylab("Count") + 
  facet_bg(fill = NA, color = NA) +
  facet_text(face = "bold", color = "black", size = 14) + 
  theme(axis.title.x = element_text(size=14, face="bold",),
        axis.title.y = element_text(size=14, face="bold",),
        title = element_text(size=14, face="bold"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(), 
        axis.text.x = element_text(face="bold", color="black"),
        axis.text.y = element_text(face="bold", color="black"),
        axis.ticks.length=unit(0.1,"cm"),
        #axis.ticks.x=element_line(size=1.1),
        axis.ticks.y=element_line(size=1.1),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        line = element_blank(),
        axis.line =  element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = .5, size = 16),
        #axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_color_manual(values = c("white", "white", "white", "white")) +
  scale_fill_manual(values = colors_line) +
  scale_x_continuous(breaks = seq(5,18,1)) + 
  expand_limits(x = c(5, 18))

```


