---
title: "Gam Analysis"
author: "Jacob DeRosa"
date: "7/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(mgcv)
library(itsadug)
library(ggplot2)
```

Factor 1: High Reward 
Factor : Snack 
Factor 3: Small/Medium Reward 
```{r}

df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% mutate(Sex = ifelse(Sex == 1, "Female", "Male")) %>% mutate(Sex = as.factor(Sex))

df$Agesq <-(df$Ages*df$Ages)

## Run age only models 
nullTC1model=(lm(TC1 ~ 1, data=df))
linTC1model=(lm(TC1 ~ Ages, data=df))
gamTC1model=(gam(TC1 ~ s(Ages, k=3, bs="ts"), method = "ML",data=df))
agepredictTC1table<-anova(nullTC1model,linTC1model,gamTC1model)
agepredictTC1table2<-anova(linTC1model,gamTC1model)

```

# ADHD Combined
```{r}

adhd_combined_nt <- df %>%
  filter(ADHD_C_NA == 1 | NT == 1) %>%
  mutate(Group = ifelse(ADHD_C_NA == 1, "ADHD Combined", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(adhd_combined_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = adhd_combined_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = adhd_combined_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = adhd_combined_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

```

```{r}

ggplot(data= adhd_combined_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "lm", size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("dodgerblue","red")) + 
  scale_color_manual(values = c("dodgerblue","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (FA1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4)

```

# ADHD Innatentive 
```{r}

adhd_inatentive_nt <- df %>%
  filter(ADHD_I_NA == 1 | NT == 1) %>%
  mutate(Group = ifelse(ADHD_I_NA == 1, "ADHD Inattentive", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(adhd_inatentive_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = adhd_inatentive_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = adhd_inatentive_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = adhd_inatentive_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

```

```{r}

ggplot(data= adhd_inatentive_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "lm", size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("green4","red")) + 
  scale_color_manual(values = c("green4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (FA1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


ggplot(data= adhd_inatentive_nt, mapping = aes(fill = Group, y=FA2, x=Ages, color=Group)) + 
  stat_smooth(method = "lm", size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("green4","red")) + 
  scale_color_manual(values = c("green4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (FA2)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


ggplot(data= adhd_inatentive_nt, mapping = aes(fill = Group, y=TC2, x=Ages, color=Group)) + 
  stat_smooth(method = "lm", size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("green4","red")) + 
  scale_color_manual(values = c("green4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC2)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",))  + 
  geom_point(alpha = .4) 



```

# Anxiety 
```{r}

anxiety_nt <- df %>%
  filter(ANX == 1 | NT == 1) %>%
  mutate(Group = ifelse(ANX == 1, "Anxiety", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))


ivnames = names(anxiety_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = anxiety_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = anxiety_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = anxiety_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

```

# Autism with ADHD 
```{r}

autism_nt <- df %>%
  filter(ASD == 1 & ADHD !=1 | NT == 1) %>%
  mutate(Group = ifelse(ASD == 1 & ADHD !=1, "ASD without ADHD", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(autism_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = autism_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = autism_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = autism_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

ggplot(data= autism_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "lm", size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("orange2","red")) + 
  scale_color_manual(values = c("orange2","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (FA1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


```

# Austism with ADHD 
```{r}

autism_adhd_nt <- df %>%
  filter(ASD == 1 & ADHD == 1 | NT == 1) %>%
  mutate(Group = ifelse(ASD == 1 & ADHD == 1, "ASD with ADHD", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(autism_adhd_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = autism_adhd_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = autism_adhd_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = autism_adhd_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)


```

# Depression 
```{r}

depression_nt <- df %>%
  filter(DEP == 1 | NT == 1) %>%
  mutate(Group = ifelse(DEP == 1, "Depression", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(depression_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = depression_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = depression_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = depression_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

```

# Learning Disorders 
```{r}

learning_nt <- df %>%
  filter(LD == 1 | NT == 1) %>%
  mutate(Group = ifelse(LD == 1, "Learning Disorder", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

ivnames = names(learning_nt)[22:26]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group, list(i = as.name(x))), data = learning_nt)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex, list(i = as.name(x))), data = learning_nt)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ Group*Sex*Ages, list(i = as.name(x))), data = learning_nt)})
sapply(model_sex_age, car::Anova,simplify =  F)

```


```{r}

cbcl <- read.csv("/Users/jacob.derosa/Documents/Github/Delay_Discounting/Data/CBCL_Cluster_df.csv") %>% select(URSI, cluster) %>% mutate(cluster = factor(cluster)) %>% inner_join(df)
ivnames = names(cbcl)[23:27]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster, list(i = as.name(x))), data = cbcl)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster*Sex, list(i = as.name(x))), data =cbcl)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster*Sex*Ages, list(i = as.name(x))), data = cbcl)})
sapply(model_sex_age, car::Anova,simplify =  F)


```


```{r}

fc_df = read.csv("/Users/jacob.derosa/Documents/Github/Delay_Discounting/Data/FC_Cluster_df.csv", header = T, sep =",") %>% mutate(cluster = factor(cluster)) %>% mutate(Sex = factor(Sex))

ivnames = names(fc_df)[14:18]

model <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster, list(i = as.name(x))), data = fc_df)})
sapply(model, car::Anova,simplify =  F)

model_sex <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster*Sex, list(i = as.name(x))), data = fc_df)})
sapply(model_sex, car::Anova,simplify =  F)

model_sex_age <- lapply(ivnames, function(x) {
  lm(substitute(i ~ cluster*Sex*Ages, list(i = as.name(x))), data = fc_df)})
sapply(model_sex_age, car::Anova,simplify =  F)


model = gam(FA3 ~ cluster + s(Ages, by = cluster, bs = "ts", k = 3), method = "REML", data = fc_df)

plot_diff(model, view="Ages",         
        comp=list(cluster=c("3", "4")),
        main='Ages window(s) of significant difference(s): 5 - 7.5')
```




