---
title: "Subtype DX Profiles"
author: "Jacob DeRosa"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(ggplot2)
library(tidyverse)

Split_1 = read.csv("/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Temp_Cluster_All.csv", header = T, sep = ",") %>% mutate(cluster= as.factor(cluster)) %>% select(-ADHD)


fc_df = read.csv("/Users/jacob.derosa/Documents/Github/Delay_Discounting/Data/FC_Cluster_df.csv", header = T, sep =",") %>% mutate(cluster = factor(cluster)) %>% mutate(Sex = factor(Sex))

dx = read.csv("C:/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% select(URSI, dx_cols)
```

```{r, fig.width= 15}

##### Diangosis Profile ######

dx_cols = Split_1[16:25]

DX_Hclust = Split_1 %>% 
  select(URSI, Sex, cluster, names(dx_cols)) %>% gather(., "DX", "Num", ADHD_I:LD, factor_key = T) %>% filter(Num != 0) %>%
  mutate(Sex = as.factor(ifelse(Sex == 0, "Male", "Female"))) %>%
  mutate(DX = as.factor(ifelse(DX == "ADHD_I", "ADHD Innatentive",
                     ifelse(DX == "ADHD_C", "ADHD Combined",
                            ifelse(DX == "NT", "Neurotypical",
                                   ifelse(DX == "ADHD_H", "ADHD Hyperactive",
                                          ifelse(DX == "LD", "Learning Disorders",
                                                 ifelse(DX == "ANX", "Anxiety",
                                                        ifelse(DX == "DEP", "Depression",
                                                               ifelse(DX == "ODD", "Oppositional Defiant",
                                                                      ifelse(DX == "Other", "Other DX", 
                                                                             ifelse(DX == "ASD", "Autism", NA)))))))))))) %>%
  within(., DX <- factor(DX, levels=names(sort(table(DX), decreasing=TRUE))))



ggplot(DX_Hclust, aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Diagnosis Counts in CBCL Subtypes") +
  xlab("") + ylab("Count")

DX_Hclust %>% filter(Sex == "Female") %>% ggplot(., aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Female Diagnosis Counts in CBCL Subtypes") +
  xlab("") + ylab("Count")

DX_Hclust %>% filter(Sex == "Male") %>% ggplot(., aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Male Diagnosis Counts in CBCL Subtypes") +
  xlab("") + ylab("Count")




```

```{r}

dx = read.csv("C:/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% select(URSI, names(dx_cols)) %>% inner_join(fc_df)

DX_Hclust = dx %>% 
  select(URSI, Sex, cluster, names(dx_cols)) %>% gather(., "DX", "Num", ADHD_I:LD, factor_key = T) %>% filter(Num != 0) %>%
  mutate(Sex = as.factor(ifelse(Sex == 0, "Male", "Female"))) %>%
  mutate(DX = as.factor(ifelse(DX == "ADHD_I", "ADHD Innatentive",
                     ifelse(DX == "ADHD_C", "ADHD Combined",
                            ifelse(DX == "NT", "Neurotypical",
                                   ifelse(DX == "ADHD_H", "ADHD Hyperactive",
                                          ifelse(DX == "LD", "Learning Disorders",
                                                 ifelse(DX == "ANX", "Anxiety",
                                                        ifelse(DX == "DEP", "Depression",
                                                               ifelse(DX == "ODD", "Oppositional Defiant",
                                                                      ifelse(DX == "Other", "Other DX", 
                                                                             ifelse(DX == "ASD", "Autism", NA)))))))))))) %>%
  within(., DX <- factor(DX, levels=names(sort(table(DX), decreasing=TRUE))))



ggplot(DX_Hclust, aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Diagnosis Counts in FC Subtypes") +
  xlab("") + ylab("Count")

DX_Hclust %>% filter(Sex == "Female") %>% ggplot(., aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Female Diagnosis Counts in FC Subtypes") +
  xlab("") + ylab("Count")

DX_Hclust %>% filter(Sex == "Male") %>% ggplot(., aes(DX)) + 
  geom_bar(fill = "cornflowerblue") + 
  geom_text(stat= "count", aes(label=..count..), hjust=-0.3, size = 3 ) + 
  ylim(0,200) +
  theme_light() +
  theme(panel.grid = element_blank()) +
  coord_flip() + 
  facet_grid(~cluster) + 
  ggtitle("Male Diagnosis Counts in FC Subtypes") +
  xlab("") + ylab("Count")




```
