---
title: "Gam Analysis"
author: "Jacob DeRosa"
date: "7/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(mgcv)
library(itsadug)
library(ggplot2)
```

Factor 1: High Reward 
Factor : Snack 
Factor 3: Small/Medium Reward 
```{r}

df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",") %>% mutate(Sex = ifelse(Sex == 1, "Female", "Male")) %>% mutate(Sex = as.factor(Sex))

df$Agesq <-(df$Ages*df$Ages)

## Run age only models 
nullTC1model=(lm(TC1 ~ 1, data=df))
linTC1model=(lm(TC1 ~ Ages, data=df))
gamTC1model=(gam(TC1 ~ s(Ages, k=3, bs="ts"), method = "ML",data=df))
agepredictTC1table<-anova(nullTC1model,linTC1model,gamTC1model)
agepredictTC1table2<-anova(linTC1model,gamTC1model)


```

# ADHD Combined
```{r}

adhd_combined_nt <- df %>%
  filter(ADHD_C_NA == 1 | NT == 1) %>%
  mutate(Group = ifelse(ADHD_C_NA == 1, "ADHD Combined", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

model = gam(FA1 ~ Group + s(Ages, by = Group, bs = "ts", k =3), method = "ML", data = adhd_combined_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ADHD Combined", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 15.6')

summary(aov(FA3 ~ Group*Ages*Sex, data = adhd_combined_nt))

```

```{r}

ggplot(data= adhd_combined_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "tp"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("dodgerblue","red")) + 
  scale_color_manual(values = c("dodgerblue","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)

summary(aov(FA1 ~ Ages*Sex*Group, data = adhd_combined_nt))

```

```{r}

model = gam(TC1 ~ Group_Sex + s(Ages, by = Group_Sex, bs = "ts"), method = "ML", data = adhd_combined_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group_Sex=c("ADHD Combined.Female", "Neurotypical.Female")),
        main='Female Ages window(s) of significant difference(s): 5 - 9.7')

ggplot(data= adhd_combined_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "tp"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("dodgerblue","red")) + 
  scale_color_manual(values = c("dodgerblue","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)



```

# ADHD Innatentive 
```{r}

adhd_inatentive_nt <- df %>%
  filter(ADHD_I_NA == 1 | NT == 1) %>%
  mutate(Group = ifelse(ADHD_I_NA == 1, "ADHD Inattentive", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

model = gam(FA1 ~ Group + s(Ages, by = Group, bs = "ts", k =3), method = "ML", data = adhd_inatentive_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ADHD Inattentive", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 8')

model = gam(FA2 ~ Group + s(Ages, by = Group, bs = "ts", k =3), method = "ML", data = adhd_inatentive_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ADHD Inattentive", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 8')


model = gam(FA3 ~ Group + s(Ages, by = Group, bs = "ts", k =3), method = "ML", data = adhd_inatentive_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ADHD Inattentive", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 8')

```

```{r}

ggplot(data= adhd_inatentive_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "tp"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("green4","red")) + 
  scale_color_manual(values = c("green4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 

ggplot(data= adhd_inatentive_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "tp"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("green4","red")) + 
  scale_color_manual(values = c("green4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)



summary(aov(FA1 ~ Group + Ages + Sex, data = adhd_inatentive_nt))
```

# Anxiety 
```{r}

anxiety_nt <- df %>%
  filter(ANX == 1 | NT == 1) %>%
  mutate(Group = ifelse(ANX == 1, "Anxiety", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))


model = gam(FA3 ~ Group + Sex + s(Ages, by = Group, bs = "ts", k=3), method = "REML", data = anxiety_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("Anxiety", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 7.3')


```

```{r}

ggplot(data= anxiety_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "tp"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("magenta4","red")) + 
  scale_color_manual(values = c("magenta4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


model = gam(TC1 ~ Group_Sex + s(Ages, by = Group_Sex, bs = "ts", k=3), method = "REML", data = anxiety_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group_Sex=c("Anxiety.Female", "Neurotypical.Female")),
        main='Ages window(s) of significant difference(s): 5 - 7.2')

ggplot(data= anxiety_nt, mapping = aes(fill = Group, y=FA1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("magenta4","red")) + 
  scale_color_manual(values = c("magenta4","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)

summary(aov(FA2 ~ Ages*Sex*Group, data = anxiety_nt))
```

# Autism with ADHD 
```{r}

autism_nt <- df %>%
  filter(ASD == 1 & ADHD !=1 | NT == 1) %>%
  mutate(Group = ifelse(ASD == 1 & ADHD !=1, "ASD without ADHD", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

model = gam(FA1 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_nt)
summary(model)


plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD without ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 7 - 21')


model = gam(FA2 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_nt)
summary(model)


plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD without ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 7 - 21')


model = gam(FA3 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_nt)
summary(model)


plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD without ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 7 - 21')


```

```{r}

ggplot(data= autism_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("orange2","red")) + 
  scale_color_manual(values = c("orange2","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


summary(aov(FA3 ~ Group + Ages + Sex, data = autism_nt))
```

# Austism with ADHD 
```{r}

autism_adhd_nt <- df %>%
  filter(ASD == 1 & ADHD == 1 | NT == 1) %>%
  mutate(Group = ifelse(ASD == 1 & ADHD == 1, "ASD with ADHD", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))


model = gam(FA1 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_adhd_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD with ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 7.2')

model = gam(FA2 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_adhd_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD with ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 7.2')


model = gam(FA3 ~ Group + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = autism_adhd_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("ASD with ADHD", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 7.2')



```

```{r}
ggplot(data= autism_adhd_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("grey47","red")) + 
  scale_color_manual(values = c("grey47","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


model = gam(TC1 ~ Group_Sex + s(Ages, by = Group_Sex, bs = "ts", k=3), method = "ML", data = autism_adhd_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group_Sex=c("ASD with ADHD.Male", "Neurotypical.Male")),
        main='Ages window(s) of significant difference(s): 5 - 7.5')

ggplot(data= autism_adhd_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("grey47","red")) + 
  scale_color_manual(values = c("grey47","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)

```

# Depression 
```{r}

depression_nt <- df %>%
  filter(DEP == 1 | NT == 1) %>%
  mutate(Group = ifelse(DEP == 1, "Depression", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))

model = gam(FA1 ~ Group + Sex + s(Ages, by = Group, bs = "ts",  k=3), method = "ML", data = depression_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("Depression", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 13.1')

model = gam(FA2 ~ Group + Sex + s(Ages, by = Group, bs = "ts",  k=3), method = "ML", data = depression_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("Depression", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 13.1')

model = gam(FA3 ~ Group + Sex + s(Ages, by = Group, bs = "ts",  k=3), method = "ML", data = depression_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("Depression", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 13.1')



```

```{r}

ggplot(data= depression_nt, mapping = aes(fill = Group, y=FA3, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3, bs = "ts"), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("black","red")) + 
  scale_color_manual(values = c("black","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 


summary(aov(FA2 ~ Group + Ages + Sex, data = depression_nt))
```

# Learning Disorders 
```{r}

learning_nt <- df %>%
  filter(LD == 1 | NT == 1) %>%
  mutate(Group = ifelse(LD == 1, "Learning Disorder", 
                        ifelse(NT == 1, "Neurotypical", NA))) %>%
  mutate(Group = as.factor(Group)) %>%
  mutate(Group_Sex = as.factor(interaction(Group, Sex)))


model = gam(TC1 ~ Group + Sex + s(Ages, by = Group, bs = "ts", k=3), method = "ML", data = learning_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group=c("Learning Disorder", "Neurotypical")),
        main='Ages window(s) of significant difference(s): 5 - 9.3')

ggplot(data= learning_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("steelblue2","red")) + 
  scale_color_manual(values = c("steelblue2","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) 



model = gam(TC1 ~ Group_Sex + s(Ages, by = Group_Sex, bs = "ts",  k=3), method = "ML", data = learning_nt)
summary(model)

plot_diff(model, view="Ages",         
        comp=list(Group_Sex=c("Learning Disorder.Male", "Neurotypical.Male")),
        main='Ages window(s) of significant difference(s): 5 - 7.5')

ggplot(data= learning_nt, mapping = aes(fill = Group, y=TC1, x=Ages, color=Group)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Group))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c("steelblue2","red")) + 
  scale_color_manual(values = c("steelblue2","red")) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) + 
  geom_point(alpha = .4) + facet_wrap(~Sex)

summary(aov(FA3 ~ Group*Ages*Sex, data = learning_nt))
```


```{r}

df_fa = df %>% select(URSI, FA1, FA2, FA3)

Split_1 = read.csv("/Users/jacob.derosa/Desktop/Scripts/Temp_Disc_Splits/Temp_Cluster_All.csv", header = T, sep = ",") %>% inner_join(df_fa) %>% mutate(cluster= as.factor(cluster))



model = gam(FA3 ~ cluster + s(Age, by = cluster, bs = "ts",  k=3), method = "REML", data = Split_1)
summary(model)

plot_diff(model, view="Age",         
        comp=list(cluster=c("3", "4")),
        main='Ages window(s) of significant difference(s): 5 - 7.5')


```

```{r}
col1 = RColorBrewer::brewer.pal(6, "Set1")

ggplot(data= Split_1, mapping = aes(fill = cluster, y=FA3, x=Age, color=cluster)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = cluster))) + 
  scale_x_continuous(breaks=seq(5, 21, 4)) +
  scale_y_continuous(breaks=seq(-2,2,1)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = c(col1)) + 
  scale_color_manual(values = c(col1)) +
  expand_limits(x=c(5,21), y =c(-2,2)) +
  labs(y = "Delay Discounting (PC1)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold",)) 

```



