---
title: "Untitled"
author: "Jacob DeRosa"
date: "9/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/CBCL_Split_Data/CBCL_subs_with_clusters.csv', header = T, sep = ",") %>% mutate(Subtype = as.factor(Subtype)) %>% select(URSI, Subtype,  starts_with("CBCL"))

df = read.csv("/Users/jacob.derosa/Desktop/Scripts/temp_disc_df.csv", header = T, sep = ",")

beh_data = merge(data, df, by = c("URSI")) %>% rename(Beh_Subtype = Subtype) %>% mutate(Beh_Subtype = as.factor(Beh_Subtype)) %>% select(URSI, Beh_Subtype, starts_with("CBCL"))# %>% mutate(Beh_Subtype = ordered(Beh_Subtype, levels = c('4','1', '2','3')))

cog_data = read.csv('C:/Users/jacob.derosa/Desktop/Scripts/cog_subs_with_clusters.csv', header = T, sep = ",") %>% mutate(Subtype = as.factor(Subtype)) %>% rename(Cog_Subtype = Subtype) #%>% mutate(Cog_Subtype = ordered(Cog_Subtype, levels = c('2','1','3'))) %>% mutate(Sex = as.factor(Sex)) 

final = merge(cog_data, beh_data, by = c("URSI")) %>% mutate(Sex = factor(ifelse(Sex == 1, "Female", "Male"))) 

final %>% group_by(Cog_Subtype) %>% summarise(mean = mean(CBCL_AP_T))

```

```{r}

ggplot(data= final, mapping = aes(fill = Beh_Subtype, y=Factor3, x=Age, color=Beh_Subtype)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Beh_Subtype))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   #scale_fill_manual(values = colors_line) + 
  #scale_color_manual(values = colors_line) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top")


```


```{r}

factors = c("Factor1", "Factor2", "Factor3")

library(mgcv)

models <- lapply(factors, function(x) {
 gam(substitute(i ~ Beh_Subtype + Cog_Subtype + Sex + s(Age, k=3), list(i = as.name(x))), method = 'REML', data = final)})
sapply(models, summary, simplify = F) 

model <- lapply(factors, function(x) {
  lm(substitute(i ~ Beh_Subtype + Age + Sex + Beh_Subtype, list(i = as.name(x))), data = final)})
sapply(model, car::Anova,simplify =  F)


```

```{r}
#these functions from the WCGNA package are great for this:
source('https://raw.githubusercontent.com/cran/WGCNA/master/R/matchLabels.R')
source('https://raw.githubusercontent.com/cran/WGCNA/master/R/accuracyMeasures.R')
hclustk4 <- paste0('H-',final$Cog_Subtype)
kClusters <- paste0('K-',final$LD)
OT<- overlapTable(hclustk4, kClusters)
#get rid of 0 values...
OT$pTable[OT$pTable == 0] <- 2e-300

textMatrix= paste(signif(OT$countTable, 2), "\n(",
                      signif(OT$pTable, 1), ")", sep= "")
dim(textMatrix)= dim(OT$countTable)
par(mar=c(10,10,10,10))
library(gplots)
heatmap.2(x= -log(OT$pTable),
          dendrogram = "none",
          Colv =F,
          Rowv = F,
          scale = c("none"),
          col="heat.colors",
          na.rm=TRUE,
          cellnote = textMatrix,
          notecol="grey30",
          notecex=0.6,
          trace=c("none"),
          cexRow = 0.8,
          cexCol = 0.8,
          main = "Cluster-Cluster Overlap",
          xlab = "K-means (k=3)",
          ylab = "TreeCut (k=3)")

```

```{r}

Y = final %>% filter(Beh_Subtype == 2 | Cog_Subtype == 1) %>% mutate(Sub = factor(ifelse(Beh_Subtype == 2 & Cog_Subtype !=1, "Beh_B", 
                                                                                         ifelse(Cog_Subtype == 1 & Beh_Subtype !=2, "Cog_B",
                                                                                                ifelse(Beh_Subtype == 2 & Cog_Subtype ==1, "Both_B", NA))))) %>% select(Factor1, Factor2, Factor3, Age, Sex, Sub, ADHD)


factors = c("Factor1", "Factor2", "Factor3")

model <- lapply(factors, function(x) {
  lm(substitute(i ~ Sub, list(i = as.name(x))), data = Y)})
sapply(model, car::Anova,simplify =  F)



ggplot(data= Y, mapping = aes(fill = Sub, y=Factor1, x=Age, color=Sub)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Sub))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = colors_line) + 
  scale_color_manual(values = colors_line) +
  expand_limits(x=c(5,18), y =c(-5, 7.5)) +
   scale_y_continuous(breaks=seq(-5, 7.5, 2)) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top")

```

```{r}


X = final %>% filter(Beh_Subtype == 4 | Cog_Subtype == 2) %>% mutate(Sub = factor(ifelse(Beh_Subtype == 4 & Cog_Subtype !=2, "Beh_G", 
                                                                                         ifelse(Cog_Subtype == 2 & Beh_Subtype !=4, "Cog_G",
                                                                                                ifelse(Beh_Subtype == 4 & Cog_Subtype ==2, "Both_G", NA))))) %>% select(Factor1, Factor2, Factor3, Age, Sex, Sub, ADHD)


factors = c("Factor1", "Factor2", "Factor3")

model <- lapply(factors, function(x) {
  lm(substitute(i ~ Sub, list(i = as.name(x))), data = X)})
sapply(model, car::Anova,simplify =  F)


ggplot(data= X, mapping = aes(fill = Sub, y=Factor1, x=Age, color=Sub)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Sub))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = colors_line) + 
  scale_color_manual(values = colors_line) +
  #expand_limits(x=c(5,18), y =c(-5, 7.5)) +
  # scale_y_continuous(breaks=seq(-5, 7.5, 2)) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top")


```

```{r}


try = rbind(X, Y)

factors = c("Factor1", "Factor2", "Factor3")

try = try %>% filter(ADHD == 1) %>% filter(Sub == "Both_G" | Sub == "Both_B")


model <- lapply(factors, function(x) {
  lm(substitute(i ~ Sub + Sex, list(i = as.name(x))), data = try)})
sapply(model, car::Anova,simplify =  F)



ggplot(data= try, mapping = aes(fill = Sub, y=Factor2, x=Age, color=Sub)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Sub))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   #scale_fill_manual(values = colors_line) + 
  #scale_color_manual(values = colors_line) +
  #expand_limits(x=c(5,18), y =c(-5, 7.5)) +
  # scale_y_continuous(breaks=seq(-5, 7.5, 2)) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top")

```

```{r}


try = X %>% filter(NT !=1)
tryn = X %>% filter(NT ==1) %>% mutate(Sub = as.factor("NT"))

try = rbind(tryn, try)


factors = c("Factor1", "Factor2", "Factor3")

try = try %>% filter(ADHD == 1) %>% filter(Sub == "Both_G" | Sub == "Both_B")


model <- lapply(factors, function(x) {
  lm(substitute(i ~ Sub + Sex, list(i = as.name(x))), data = try)})
sapply(model, car::Anova,simplify =  F)


ggplot(data= try, mapping = aes(fill = Cog_Subtype, y=Factor1, x=Age, color=Cog_Subtype)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Cog_Subtype))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   #scale_fill_manual(values = colors_line) + 
  #scale_color_manual(values = colors_line) +
  #expand_limits(x=c(5,18), y =c(-5, 7.5)) +
  # scale_y_continuous(breaks=seq(-5, 7.5, 2)) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top")

```

```{r}


Y = final %>% filter(Beh_Subtype == 2 | Cog_Subtype == 1) %>% mutate(Sub = factor(ifelse(Beh_Subtype == 2 & Cog_Subtype !=1, "Beh", 
                                                                                         ifelse(Cog_Subtype == 1 & Beh_Subtype !=2, "Cog",
                                                                                                ifelse(Beh_Subtype == 2 & Cog_Subtype ==1, "Bad", NA))))) %>% select(Factor1, Factor2, Factor3, Age, Sex, Sub, ASD, NT) %>% filter(Sub == "Bad")


X = final %>% filter(Beh_Subtype == 4 | Cog_Subtype == 2) %>% mutate(Sub = factor(ifelse(Beh_Subtype == 4 & Cog_Subtype !=2, "Beh", 
                                                                                         ifelse(Cog_Subtype == 2 & Beh_Subtype !=4, "Cog",
                                                                                                ifelse(Beh_Subtype == 4 & Cog_Subtype ==2, "Good", NA))))) %>% select(Factor1, Factor2, Factor3, Age, Sex, Sub, ASD, NT) %>% filter(Sub == "Good")



colors_line = c(scales::alpha("#C777E9", 1),
                scales::alpha("dodgerblue2", 1),
                scales::alpha("#FF9100", 1),
                scales::alpha("#2F7600", 1))

try = rbind(X, Y)

model <- lapply(factors, function(x) {
  lm(substitute(i ~ Sub + Age + Sex, list(i = as.name(x))), data = try)})
sapply(model, car::Anova,simplify =  F)


ggplot(data= try, mapping = aes(fill = Sub, y=Factor1, x=Age, color=Sub)) + 
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3), size =1.5, fullrange = T, se = T, alpha = .2, (aes(color = Sub))) + 
  scale_x_continuous(breaks=seq(6, 18, 2)) +
  theme(axis.line = element_line(size=2, colour = "black"),
        panel.grid.major = element_line(colour = "#d3d3d3"), panel.grid.minor = element_blank(),
        panel.border = element_blank(), panel.background = element_blank()) +
  theme(panel.grid.major = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(), 
    axis.text.x = element_text(face="bold", color="black", 
                           size=15, vjust=.5,),
          axis.text.y = element_text(face="bold", color="black", 
                           size=15),
    axis.ticks.length=unit(0.3,"cm"),
    axis.ticks.x=element_line(size=2),
    axis.ticks.y=element_line(size=2)) + 
  theme(legend.title = element_text(size = 14, face = "bold",), 
    legend.text = element_text(size = 12, face = "bold",)) + 
   scale_fill_manual(values = colors_line) + 
  scale_color_manual(values = colors_line) +
  #expand_limits(x=c(5,18), y =c(-5, 7.5)) +
   #scale_y_continuous(breaks=seq(-5, 7.5, 2)) +
  labs(y = "DD Factor 3 (Smaller Sooner)", x = "Chronological Age") +
  theme(axis.title.x = element_text(size=16, face="bold",),
        axis.title.y = element_text(size=16, face="bold",),
        title = element_text(size=14, face="bold")) + 
  #geom_point(alpha = .4) +
  theme(legend.position = "top") + facet_wrap(~ASD)

#table(try$ANX, try$Sub)

#model = gam(Factor1 ~ Sub + Sex + s(Age, k=3) + s(Age, by = Subtype, k=3), method = "REML", data =data_1) %>% mutate(Subtype = ordered(Subtype, levels = c('3','1','2'))) %>% mutate(Sex = as.factor(Sex)) 
#summary(model)

#library(itsadug)

#plot_diff(model, view="Age", comp=list(Subtype=c("1", "3")), main='Age window(s) of significant difference(s)')



```

c("URSI", "X", "Cog_Subtype", "WIAT_Num_Stnd", "WIAT_Pseudo_Stnd", 
"WIAT_Spell_Stnd", "WIAT_Word_Stnd", "WIAT_LCODC_Stnd", "WIAT_LC_Stnd", 
"WIAT_RC_Stnd", "WIAT_MP_Stnd", "WISC_VSI", "WISC_VCI", "WISC_FRI", 
"WISC_WMI", "WISC_PSI",

)

```{r}

IQ = read.csv("C:/Users/jacob.derosa/Desktop/Scripts/Release8/IQ.csv")
final = merge(IQ, final, by = c("URSI")) 

summary(gam(Factor1 ~ s(Age) + WIAT_LCODC_Stnd + IQ, method = "REML", data = final))
summary(gam(Factor1 ~ s(Age) + WIAT_LC_Stnd + IQ, method = "REML", data = final))

summary(gam(Factor1 ~ s(Age) + CBCL_AP_T, method = "REML", data = final))


summary(aov(Factor1 ~ Beh_Subtype + Age + Sex + WIAT_LCODC_Stnd + IQ, data = final))


summary(aov(Factor1 ~ Cog_Subtype + Age + Sex + CBCL_AP_T + IQ, data = final))

```

```{r}
measures = c("CBCL_AP_T", "CBCL_RBB_T", "CBCL_AB_T", "CBCL_WD_T", "CBCL_SC_T", "CBCL_TP_T", "CBCL_AD_T", "CBCL_SP_T", "Age", "IQ")

model <- lapply(measures, function(x) {
  lm(substitute(i ~ Cog_Subtype, list(i = as.name(x))), data = final)})
sapply(model, car::Anova,simplify =  F)

```
